In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("C:/Users/admin/Downloads/churndata.csv")
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...    pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...      0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...      0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...      1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...      0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [3]:
df.describe()

tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless    longmon     ...           pager  \
count  200.000000  200.000000  200.000000  200.00000     ...      200.000000   
mean     0.425000    0.705000    0.290000   11.78925     ...        0.275000   
std      0.495584    0.457187    0.454901    9.88725     ...        0.447635   
min      0.000000    0.000000    0.000000    1.10000     ...        0.000000   
25%      0.000000    0.000000    0.000000    5.53750     ...        0.000000   
50%      0.000000    1.000000    0.000000    8.25000     ...        0.000000   
75%      1.000000    1.000000    1.000000   14.30000     ...        1.000000   
max      1.000000    1.000000    1.000000   62.30000     ...        1.000000   

         internet   callwait      confer       ebill     loglong     logtoll  \
count  200.000000  200.00000  200.000000  200.000000  200.000000  200.000000   
mean     0.440000    0.45500    0.460000    0.440000    2.193285    3.229185   
std      0.497633    0.49922    0.499648    0.497633    0.731282    0.281019   
min      0.000000    0.00000    0.000000    0.000000    0.095000    1.749000   
25%      0.000000    0.00000    0.000000    0.000000    1.711750    3.226500   
50%      0.000000    0.00000    0.000000    0.000000    2.110000    3.240000   
75%      1.000000    1.00000    1.000000    1.000000    2.660000    3.240000   
max      1.000000    1.00000    1.000000    1.000000    4.132000    4.227000   

            lninc     custcat       churn  
count  200.000000  200.000000  200.000000  
mean     3.951015    2.475000    0.290000  
std      0.752553    1.079445    0.454901  
min      2.197000    1.000000    0.000000  
25%      3.434000    2.000000    0.000000  
50%      3.871000    2.000000    0.000000  
75%      4.382000    3.000000    1.000000  
max      7.419000    4.000000    1.000000  

[8 rows x 28 columns]

In [4]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
tenure      200 non-null float64
age         200 non-null float64
address     200 non-null float64
income      200 non-null float64
ed          200 non-null float64
employ      200 non-null float64
equip       200 non-null float64
callcard    200 non-null float64
wireless    200 non-null float64
longmon     200 non-null float64
tollmon     200 non-null float64
equipmon    200 non-null float64
cardmon     200 non-null float64
wiremon     200 non-null float64
longten     200 non-null float64
tollten     200 non-null float64
cardten     200 non-null float64
voice       200 non-null float64
pager       200 non-null float64
internet    200 non-null float64
callwait    200 non-null float64
confer      200 non-null float64
ebill       200 non-null float64
loglong     200 non-null float64
logtoll     200 non-null float64
lninc       200 non-null float64
custcat     200 non-null float64
chur

(200, 28)

In [5]:
#data preprocessing 
#identifying missing values
import numpy as np

# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.head(5)
missing_data = df.isnull()
missing_data.head(5)
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")    
    #there is no missing values

tenure
False    200
Name: tenure, dtype: int64

age
False    200
Name: age, dtype: int64

address
False    200
Name: address, dtype: int64

income
False    200
Name: income, dtype: int64

ed
False    200
Name: ed, dtype: int64

employ
False    200
Name: employ, dtype: int64

equip
False    200
Name: equip, dtype: int64

callcard
False    200
Name: callcard, dtype: int64

wireless
False    200
Name: wireless, dtype: int64

longmon
False    200
Name: longmon, dtype: int64

tollmon
False    200
Name: tollmon, dtype: int64

equipmon
False    200
Name: equipmon, dtype: int64

cardmon
False    200
Name: cardmon, dtype: int64

wiremon
False    200
Name: wiremon, dtype: int64

longten
False    200
Name: longten, dtype: int64

tollten
False    200
Name: tollten, dtype: int64

cardten
False    200
Name: cardten, dtype: int64

voice
False    200
Name: voice, dtype: int64

pager
False    200
Name: pager, dtype: int64

internet
False    200
Name: internet, dtype: int64

callwait
False    200
Name: 

In [6]:
df.corr()

tenure       age   address    income        ed    employ  \
tenure    1.000000  0.431802  0.456328  0.109383 -0.070503  0.445755   
age       0.431802  1.000000  0.746566  0.211275 -0.071509  0.622553   
address   0.456328  0.746566  1.000000  0.132807 -0.145550  0.520926   
income    0.109383  0.211275  0.132807  1.000000  0.141241  0.345161   
ed       -0.070503 -0.071509 -0.145550  0.141241  1.000000 -0.213886   
employ    0.445755  0.622553  0.520926  0.345161 -0.213886  1.000000   
equip    -0.117102 -0.071357 -0.148977 -0.010741  0.488041 -0.174470   
callcard  0.426530  0.170404  0.209204 -0.019969 -0.071178  0.266612   
wireless -0.070590 -0.065527 -0.146478 -0.029635  0.267670 -0.101187   
longmon   0.763134  0.373547  0.421782  0.041808 -0.072735  0.363386   
tollmon   0.100214  0.053595 -0.015564 -0.003701 -0.000712  0.117962   
equipmon -0.043274 -0.030402 -0.125212  0.000275  0.492999 -0.141651   
cardmon   0.489857  0.203202  0.297395 -0.013513 -0.070990  0.219413   
wiremon   0.043067 -0.003685 -0.113143 -0.027998  0.288571 -0.045539   
longten   0.796355  0.393370  0.447256  0.048374 -0.083032  0.385254   
tollten   0.398869  0.187221  0.129141 -0.000262 -0.016257  0.240498   
cardten   0.676920  0.336903  0.406964  0.019358 -0.069499  0.309183   
voice    -0.050686  0.019555 -0.069627  0.085525  0.233628 -0.035922   
pager     0.018791  0.006803 -0.105812  0.056977  0.258698  0.038381   
internet -0.164921 -0.078395 -0.191058  0.102809  0.552996 -0.250044   
callwait -0.009747  0.020002 -0.019967  0.081133 -0.016247  0.119708   
confer    0.080650  0.030625 -0.030494 -0.031556 -0.132215  0.173247   
ebill    -0.099128 -0.048279 -0.172171 -0.041392  0.427315 -0.151965   
loglong   0.864388  0.379413  0.409357  0.065595 -0.054581  0.377186   
logtoll   0.310045  0.093600  0.018386 -0.156498 -0.007227  0.068718   
lninc     0.246353  0.313359  0.212929  0.680313  0.206718  0.540052   
custcat   0.134237  0.041055 -0.016841  0.030725  0.013127  0.131292   
churn    -0.376860 -0.287697 -0.260659 -0.090790  0.216112 -0.337969   

             equip  callcard  wireless   longmon    ...        pager  \
tenure   -0.117102  0.426530 -0.070590  0.763134    ...     0.018791   
age      -0.071357  0.170404 -0.065527  0.373547    ...     0.006803   
address  -0.148977  0.209204 -0.146478  0.421782    ...    -0.105812   
income   -0.010741 -0.019969 -0.029635  0.041808    ...     0.056977   
ed        0.488041 -0.071178  0.267670 -0.072735    ...     0.258698   
employ   -0.174470  0.266612 -0.101187  0.363386    ...     0.038381   
equip     1.000000 -0.087051  0.386735 -0.097618    ...     0.308633   
callcard -0.087051  1.000000  0.220118  0.322514    ...     0.251069   
wireless  0.386735  0.220118  1.000000 -0.073043    ...     0.667535   
longmon  -0.097618  0.322514 -0.073043  1.000000    ...    -0.001372   
tollmon  -0.090516  0.352994  0.462751  0.083771    ...     0.499124   
equipmon  0.941065  0.026955  0.527573 -0.070876    ...     0.461458   
cardmon  -0.056590  0.629955  0.195387  0.493439    ...     0.216653   
wiremon   0.367579  0.259638  0.885879 -0.020392    ...     0.704724   
longten  -0.098271  0.342553 -0.088461  0.984808    ...    -0.011369   
tollten  -0.097151  0.292555  0.328256  0.338036    ...     0.390620   
cardten  -0.053837  0.448182  0.047773  0.673179    ...     0.097579   
voice     0.264481  0.226109  0.649721 -0.080503    ...     0.608335   
pager     0.308633  0.251069  0.667535 -0.001372    ...     1.000000   
internet  0.623509 -0.067146  0.343631 -0.223929    ...     0.266193   
callwait -0.034021  0.370878  0.389670  0.032913    ...     0.426690   
confer   -0.103499  0.311056  0.382925  0.060614    ...     0.352743   
ebill     0.603133 -0.045058  0.321433 -0.124605    ...     0.288752   
loglong  -0.113065  0.351030 -0.042637  0.901631    ...     0.015771   
logtoll  -0.027882  0.080060  0.178317  0.247302    ...     0.231647   
lninc     0.083494  0.156920  0.033558  0.122550   

In [7]:
df.corr()["churn"][:-1]

tenure     -0.376860
age        -0.287697
address    -0.260659
income     -0.090790
ed          0.216112
employ     -0.337969
equip       0.275284
callcard   -0.311451
wireless    0.174356
longmon    -0.292026
tollmon     0.014356
equipmon    0.255348
cardmon    -0.177163
wiremon     0.177483
longten    -0.294906
tollten    -0.059482
cardten    -0.228634
voice       0.142315
pager       0.124623
internet    0.254838
callwait   -0.052885
confer     -0.081361
ebill       0.254838
loglong    -0.336869
logtoll    -0.070156
lninc      -0.117459
custcat     0.014839
Name: churn, dtype: float64

In [8]:
print(df.columns)
df["churn"]=df["churn"].astype("int")
df.dtypes

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')


tenure      float64
age         float64
address     float64
income      float64
ed          float64
employ      float64
equip       float64
callcard    float64
wireless    float64
longmon     float64
tollmon     float64
equipmon    float64
cardmon     float64
wiremon     float64
longten     float64
tollten     float64
cardten     float64
voice       float64
pager       float64
internet    float64
callwait    float64
confer      float64
ebill       float64
loglong     float64
logtoll     float64
lninc       float64
custcat     float64
churn         int32
dtype: object

In [9]:
x=np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip','internet']])
y=np.asarray(df["churn"])
x[0:5]

y[0:5]

array([1, 1, 0, 0, 0])

In [10]:
#normalize our datasets
from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695, -0.88640526],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -0.88640526],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -0.88640526],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  1.12815215],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695, -0.88640526]])

In [11]:
#we will split our datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 8) (160,)
Test set: (40, 8) (40,)


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,jaccard_similarity_score,log_loss
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
y=np.reshape(1,-1)
#Now we can predict using our test set:
pred=LR.predict(X_test)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1])

In [14]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.52365062, 0.47634938],
       [0.61789034, 0.38210966],
       [0.57529875, 0.42470125],
       [0.64883209, 0.35116791],
       [0.57895489, 0.42104511],
       [0.56686185, 0.43313815],
       [0.54211878, 0.45788122],
       [0.6163585 , 0.3836415 ],
       [0.39572843, 0.60427157],
       [0.60671562, 0.39328438],
       [0.56251102, 0.43748898],
       [0.6057083 , 0.3942917 ],
       [0.49207749, 0.50792251],
       [0.41114102, 0.58885898],
       [0.67087921, 0.32912079],
       [0.56733382, 0.43266618],
       [0.50032416, 0.49967584],
       [0.46939416, 0.53060584],
       [0.47336409, 0.52663591],
       [0.54375417, 0.45624583],
       [0.62891165, 0.37108835],
       [0.50611527, 0.49388473],
       [0.65220187, 0.34779813],
       [0.50309069, 0.49690931],
       [0.48478403, 0.51521597],
       [0.71783959, 0.28216041],
       [0.57247951, 0.42752049],
       [0.50125448, 0.49874552],
       [0.53398551, 0.46601449],
       [0.72513963, 0.27486037],
       [0.

In [15]:
jaccard_similarity_score(y_test, pred)

0.725

In [16]:
# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test,pred, labels=[1,0])
np.set_printoptions(precision=2)
print(cnf_matrix)


[[ 7  8]
 [ 3 22]]


In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print (classification_report(y_test, pred))


             precision    recall  f1-score   support

          0       0.73      0.88      0.80        25
          1       0.70      0.47      0.56        15

avg / total       0.72      0.72      0.71        40



In [18]:
log_loss(y_test, yhat_prob)

0.598228952835334